name: Deploy Static Site to GitHub Pages

on: push: branches: - main

jobs: build-and-deploy: runs-on: ubuntu-latest

steps:
  # Checkout the repository
  - name: Checkout repo
    uses: actions/checkout@v3
    with:
      # Allow the gh-pages action to push
      persist-credentials: false
      fetch-depth: 0

  # Setup Python environment
  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.x'

  # Install dependencies
  - name: Install dependencies
    run: |
      pip install --upgrade pip
      pip install markdown jinja2

  # Generate static site
  - name: Generate site
    run: python generate_site.py

  # Deploy to gh-pages
  - name: Deploy to GitHub Pages
    uses: peaceiris/actions-gh-pages@v3
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./site
      # Optional: set user identity
      # committer_name: github-actions
      # committer_email: github-actions@github.com
